[flyway]
locations = ["filesystem:migrations"]

[environments.default]
url = "jdbc:mysql://localhost:33061/belajardb?useSSL=false&allowPublicKeyRetrieval=true"
user = "belajar"
password = "belajar123"